### PR TITLE
Restructured box plot grouping

### LINKED ISSUE #330: Rethink plot grouping by ProteinID
Currently, you can (e.g. after imputation) choose to group by ProteinId in the BoxPlot. Seeing as there are hundreds of them, the graph doesn't provide any useful information / is too densely packed. This decision should be resconsidered, for example by allowing the user to choose specific proteins to be shown in the plot, or some sort of metric (e.g. the ProteinIDs with most imputations) that they are ranked and then chosen to be displayed by. 

## Acceptance Criteria
- [ ] It is no longer possible to show this useless graph.
- [ ] there is a way to select proteins to be displayed
- [ ] there is an automatic choice of e.g. 10 proteins which are displayed.

### PR DESCRIPTION
**Pull request by RogerAK**
## Description
fixes #330 
Added an option for the user to select a group of proteins, which can be used to plot a box plot

## Changes

1. workflow_meta: Added a Category for all the methods, where a box plot can be plotted
2. imputation, normalisation, transformation, plots: added a parameter for proteins_of_interest
3. Fields: it calls the function special_params from runs_helper to update the protein ID in the dynamic view
4. Also updated the test to the new structure

## Testing
1. Go through the preprocessing section and try plotting box plot in imputation, normalisation and transformation methods

## PR checklist
**Development**
- [x] If necessary, I have updated the documentation (README, docstrings, etc.)
- [x] If necessary, I have created / updated tests.
 
**Mergeability**
- [x] main-branch has been merged into local branch to resolve conflicts
- [x] The tests and linter have passed AFTER local merge
- [x] The code has been formatted with `black`
 
**Code review**
- [x] I have self-reviewed my code.
- [ ] At least one other developer reviewed and approved the changes

### CODE REVIEW

**Review by antonneubauer — CHANGES_REQUESTED** [review]
Overall this seems quite nice to me. I have two major notes (that i postet into the conversations before):


- it is now impossible to plot all proteins because the request gets too large. I think there might be a usecase for plotting even a very large number of proteins when trying to get a feeling for the data. E.g.: plotting all proteins to see if and where outliers exist and how they compare to the rest of the dataset. I do not think that taking away functionality because it looks weird is a good idea. There might be use cases that we cannot think of right now. As the request size is a technical limitation, you might have to change the way the selected proteins are transmitted, all given that this is indeed something you want to fix.
- for me, only one protein gets selected automatically (the first one, i think), not 10 as suggested in the issue. 10 might be too many but automatically selecting more than one is a good idea IMO as that immediately signals to the user that multiple can be selected

I have added some notes to the individual files but one thing i would like to suggest is writing all the function calls in the tests with keyword arguments where possible. In a few places you misplaced the added arguments and even though the tests still work, i think it would be good to clear that up. And since you are touching those tests anyways, might as well do it now i figured.

All the notes aside: this works well and I am, of course, happy to discuss any of the points i made :)

**Review by antonneubauer — CHANGES_REQUESTED** [review]
aside from that one 5 that i don't quite understand, this looks good and is ready from my point of view

**Comment by henninggaertner** [comment]
@RogerAK arbeitest du noch hier dran?

**Comment by RogerAK** [comment]
Created a new pull request, because this one is based on the old architecture of PROTzilla

**Pull request closed without merging**
